henry2004y/TestParticle.jl

- src/TestParticle.jl
- test/runtests.jl
1. I have modified the getinterp function to a closure function to return a field function which is similar to analytical field. Meanwhile, those redundant functions were deleted.
2. Fixing the function names in the test sets.
3. Adding a type judgement to prepare function for supporting the mixture of different type of fields.
4. Adding a simple test set about mixed fields.
> unify the trace functions of numerical and analytical fields

- .github/workflows/benchmark.yml
- benchmark/benchmarks.jl
- benchmark/runbench.jl
- src/TestParticle.jl
- test/runtests.jl
1. Adding support for time-dependent fields. Adding abstract type `AbstractField` and struct `Field`.
2. Unifying the interfaces of trace and trace_full. Adding two types of Tuple.
3. Adding related tests.
4. Improving performance.
Thanks to @henry2004y. And the work for the interfaces is finished.
> add support for time-dependent fields and unify the interfaces of `trace` and `trace_full`

- src/TestParticle.jl
- test/runtests.jl
* Add support for normalized units in gyrofrequency. Many numerical simulation outputs are saved in normalized units, which requires proper conversion to do tracing. Typical ones require a length scale $l_0$, time scale $t_0$, and magnetic field scale $B_0$. Most often the time scale is chosen to be 1 s, so the only scale required in the Lorentz force is $\Omega_0 = qB_0/m$. The electric fields have units of $\mathbf{v}\times\mathbf{B}$.
$$
\frac{d\mathbf{v}^\prime}{dt^\prime} = \Omega_0 t_0 (\mathbf{E}^\prime + \mathbf{v}^\prime \times\mathbf{B}^\prime)
$$
* Handle #41, 
* Merge docs for dispatched methods
* Explicitly list all the imported methods from Interpolation.jl.
> Support normalized units and 2D fields

- .github/workflows/CI.yml
- .github/workflows/RecipeCI.yml
- .github/workflows/benchmark.yml
- docs/Project.toml
- docs/src/index.md
- docs/src/tutorial.md
I managed to add WGLMakie output to the doc directly by basically copying the scripts from the example folder. This looks pretty good. Due to [current limitations](https://docs.makie.org/stable/documentation/backends/wglmakie/#output), 2D outputs are static, while single frame 3D outputs are interactive. This will surely be improved in the future. What do you think @TCLiuu? We may add more examples in this way.
> Add WGLMakie output to doc

- src/TestParticle.jl
- test/runtests.jl
Taking Meshes types into `prepare` is like a round tour; we may simply pass ranges directly for numerical grids.
> Add direct support for ranges

- dependabot.yml
This allows to get updates for GitHub actions automatically. After merging this, we could also enable other Dependabot actions in 'Settings -> Code security and analysis -> Dependabot alerts' and '... -> Dependabot security updates'.
> Enable dependabot for GitHub actions

- examples/demo_magneticmirror.jl
- src/utility/confinement.jl
1. Fixed a serious bug related to  magnetic field calculation of magnetic mirror.
This bug will cause serious divergence at the center axis of the magnetic field. #73 may require recalculating the relevant calculations involving magnetic mirrors.
2. Add  a new example base on a magnetic mirror.
From the third figure on the right, it can be seen that the zero-order quantity of magnetic moment is conserved, but its high-order part is not conserved under this definition of magnetic moment and oscillates rapidly. We can observe from this the oscillation characteristics of magnetic moments at different levels.
The bug fixed in the first item will cause magnetic moment non-conservation, as mentioned in #72.
> Add an example based on magnetic mirror 

- docs/examples/basics/config.json
- docs/examples/basics/demo_boris.jl
- docs/examples/basics/demo_proton_dipole.jl
- src/TestParticle.jl
- src/pusher.jl
- test/runtests.jl
It's time to add some native particle pushers in the package!
The Boris method is the de facto particle pusher in plasma physics, because of its excellent conservation behavior and relative simplicity. The Boris method is a second order method with discrete phase error related to the choice of fixed time step. If the time step is not fixed, this method can still be used, but the conservation of phase space trajectory will be violated.
The Boris method is specifically designed for the expression of Lorentz force. A general ODE solver in OrdinaryDiffEq.jl does not take into account the special form of the Lorentz equation, which is also the reason why the Boris method does not exist in OrdinaryDiffEq.jl. With my recent tests on multiple algorithms from OrdinaryDiffEq.jl, the default …
> Add native Boris method

- src/TestParticle.jl
For handling the analytical field and numerical field consistently in `prepare`, I would suggest moving the `Field` construction outisde of `getinterp` for the numerical field.
> Move Field construction outside of getinterp

- src/TestParticle.jl
- src/pusher.jl
* Use charge-mass ratio instead of charge and mass separately for speed
* Replace the `cross` function with handwritten expression
> Speeding up the kernel

- Project.toml
- docs/examples/basics/config.json
- docs/examples/basics/demo_dimensionless_periodic.jl
- src/TestParticle.jl
- test/runtests.jl
* When dealing with periodic boundaries, it is almost always correct to use `OnCell()` instead of `OnGrid()`.
* Add a new argument `bc` to allow switching between periodic BC and NaN BC.
> Add option to choose BC types for numerical fields

- docs/examples/basics/config.json
- docs/examples/basics/demo_output_func.jl
- docs/examples/basics/demo_savingcallback.jl
Unfortunately, `SavingCallback` from DiffEqCallbacks.jl does not seem to be compatible with `EnsembleProblem`. For ensemble problems, we can work around this issue by using the `output_func` argument.
> Add demos with additional diagnostics

- Project.toml
- benchmark/benchmarks.jl
- docs/examples/basics/demo_dimensionless.jl
- docs/examples/basics/demo_dimensionless_dimensional.jl
- docs/examples/basics/demo_dimensionless_periodic.jl
- docs/examples/basics/demo_output_func.jl
- docs/examples/basics/demo_savingcallback.jl
- src/TestParticle.jl
- test/runtests.jl
Treat dimensionless tracing in a consistent manner. Although the previous version partially works, it's so easy to confuse ourselves about the input and output units. Instead of relying on one single normalization factor for the pure-B tracing cases, we should instead normalize E and B fields separately. The updated `prepare` function can be simplified with the "correct" normalization process. `trace_normalized!` is actually simpler since all the normalizations are embedded inside E and B fields.
> Fix dimensionless tracing

- benchmark/benchmarks.jl
- src/pusher.jl
Current implementation of the Boris ensemble pusher triggers quite a lot memory allocations, which in turn triggers GC more frequently when running with multithreading (#127). This PR tries to reduce the allocations a bit by assuming that the timestep, EM fields, and particle properties are constant within one batch tracing.
> Refactor Boris ensemble tracing

- docs/examples/basics/demo_boris.jl
- docs/examples/basics/demo_proton_dipole.jl
* Fix an error in gyroperiod calculation
* Redesign the Boris demo to show phase errors at larger time steps.
Related to #132
> Redesign Boris demo

- Project.toml
- docs/examples/advanced/demo_shock.jl
- docs/examples/basics/demo_multiple.jl
- src/TestParticle.jl
- src/precompile.jl
- src/sampler.jl
- src/utility/utility.jl
- test/runtests.jl
Our current implementation of Maxwellian sampling is wrong. This PR fixes the sampling and improve the shock demo.
The new sampling is based on the Box-Muller method. We remove the option of `nparticles` inputs since it's less frequently used in practice, although it's supposed to be faster.
Since we are sampling in each 1D direction separately, we should follow the 1D thermal speed equation.
* Use `vth` for thermal speed instead of `uth`. 
#150
> Fix Maxwellian sampling

- .github/workflows/CI.yml
It is claimed to be [faster than the previous cache action](https://discourse.julialang.org/t/this-month-in-julia-world-2024-01/109549).
> Use Julia's cache action

- Project.toml
- src/pusher.jl
Fix an issue that causes an end point mismatch in the Boris pusher: we no longer force to have an exact end time at `tspan[2]`.
> Fix time length mismatch

- Project.toml
- src/TestParticle.jl
- src/utility/utility.jl
In Meshes.jl v0.43, `coordinates` is renamed to `coords`. Also, Units.jl is integrated into the type system, so there are quite many changes.
> Bump meshes compatibility

- docs/examples/advanced/demo_shock.jl
Since Makie v0.21, there is an internal check for unsatisfied keywords. It happened that the `strokecolor` keyword from PairPlots.jl has some issues.
> Remove undefined Makie recipe keywords

- benchmark/benchmarks.jl
- docs/examples/advanced/demo_proton_dipole.jl
- docs/examples/basics/demo_dimensionless.jl
- docs/examples/basics/demo_dimensionless_dimensional.jl
- src/TestParticle.jl
- src/equations.jl
- src/utility/utility.jl
- test/runtests.jl
Handle #198 by switching to solve "momentum" $\vec{p}/m = \gamma \vec{v}$ instead of $\vec{v}$ in the relativistic case. In this way we do not need to check whether the computed velocity is larger than the speed of light, since [the derivation](http://spiff.rit.edu/classes/phys150/lectures/mom_rel/isolate_v.html) guarantees smaller than c speed. A small caveat is that when velocity is 0, the direction is undetermined, which requires an additional branch.
As quoted from the original discussion note, this form is a bit unintuitive and requires a conversion from relativistic momentum to velocity in certain cases. However, I feel like it is more natural with relativity. Further discussions are welcomed! @Beforerr 
The normalization case may need further testing.
> Relativistic momentum

- .github/workflows/benchmark.yml
- benchmark/runbench.jl
Test if benchmarking with AirspeedVelocity.jl gives better workflow.
Features that I enjoy:
1. Benchmark results are updated instead of posting a new one after each new push.
2. Result table is concise 
Feature I wish to have:
1. Memory allocation check (used to be there in PkgBenchmark.jl).
> Benchmarking via AirspeedVelocity

- .github/workflows/benchmark.yml
- Project.toml
- benchmark/benchmarks.jl
- src/equations.jl
- src/precompile.jl
- test/runtests.jl
Check if the usage of `SVector` is helpful in all cases.
> Use SVector in all trace methods

- Project.toml
- docs/examples/advanced/demo_gc.jl
- docs/examples/basics/demo_ExB_drift.jl
- docs/examples/basics/demo_FLR.jl
- docs/examples/basics/demo_curvature_B.jl
- docs/examples/basics/demo_gradient_B.jl
- docs/examples/basics/demo_polarization_drift.jl
- src/TestParticle.jl
- src/equations.jl
- src/gc.jl
- test/runtests.jl
* Rename previous `get_gc` that returns a function to `get_gc_func`
* Replace views with SA indexing (inspired by the suggestions of @Beforerr)
---
It is also good to see that solving GC equations is not actually slower than brute-force tracing. Unnecessary allocation is removed from `trace_gc_1st!`.
> Split gc functions

- src/equations.jl
- src/prepare.jl
The idea is that is we know something is zero we can make calculation simpler. A example is given below
```
using TestParticle, StaticArrays
using TestParticle: ZeroField
uniform_B(x) = SA[0.0, 0.0, 1e-8]
uniform_E(x) = SA[0.0, 0.0, 0.0]
zero_E = ZeroField()
stateinit = let x0 = [1.0, 0, 0], v0 = [0.0, 1.0, 0.1]
[x0..., v0...]
end
param = prepare(uniform_E, uniform_B, species=Proton)
@code_typed trace(stateinit, param, 0.0)
param2 = prepare(zero_E, uniform_B, species=Proton)
@code_typed trace(stateinit, param2, 0.0)
```
Original `@code_typed` info
```
julia> @code_typed trace(stateinit, param, 0.0)
CodeInfo(
1 ── %1  = Base.getfield(p, 1)::Float64
│    %2  = StaticArrays.getfield($(QuoteNode([4, 5, 6])), :data)::Tuple{Int64, Int64, Int64}
│    %3  = $(Expr(:boundscheck, true))::Bool
│ …
```
> feat: introduce ZeroField for better performance

- .github/workflows/benchmark.yml
Yesterday when a contributor tried to submit PRs, all the benchmark workflows failed at posting the result comments. This PR tries to use `pull_request_target` instead of `pull_request` and also set the write permission on the script top level.
> Use pull_request_target for Benchmarks

- docs/examples/advanced/demo_fermi_foreshock.jl
- docs/examples/advanced/demo_output_func.jl
- docs/examples/advanced/demo_savingcallback.jl
- docs/examples/basics/demo_Buniform_Ezero.jl
- docs/examples/basics/demo_ExB_drift.jl
- docs/examples/basics/demo_FLR.jl
- docs/examples/basics/demo_boris.jl
- docs/examples/basics/demo_energy_conservation.jl
- docs/examples/basics/demo_gradient_B.jl
- src/equations.jl
- src/gc.jl
- src/prepare.jl
- src/pusher.jl
Julia compiler is sooooo smart that when `F` is `ZeroField()` the typed codes is exactly the same with previous `TPTuple` codes so now unification comes with no runtime cost.
Now `prepare(args...; kwargs...)` always return `(q2m, m, E, B, F)`
> refactor: unify `prepare` and `trace` interface
