- src/TestParticle.jl
- test/runtests.jl
1. After lots of tests, I chose Eq.(2) in #34 as the equations of motion.
2. I have rewritten the error message of FTLError. @henry2004y, can you help me review the expression?
3. The purpose of the new test case is to verify whether the energy of electron is the same as expected. So an algorithm with higher accuracy like `Vern6` is necessary.
And, I want to attach a [song](https://www.youtube.com/watch?v=6_eKJysJk1Y).
> relativistic particle

- TestParticleMakie/License
Add MIT license to TestParticleMakie.
> Add license to TestParticleMakie

- TestParticleMakie/src/interactive.jl
- docs/src/example.md
- test/runtests.jl
Add robust boundary checking method and format some codes.
> Out of domain

- Project.toml
- README.md
- TestParticleMakie/Project.toml
- TestParticleMakie/README.md
- docs/src/plotfunctions.md
- Add quick short descriptions in the README files.
- Bump Makie and Meshes versions.
> Extend README

- src/TestParticle.jl
- test/runtests.jl
Order of interpolation can now be chosen from 1 (default), 2, and 3.
> Add order option for interpolation

- .github/workflows/TagBot.yml
- src/TestParticle.jl
- test/runtests.jl
Allow direct range inputs for dimensional 2D fields.
> Add a new method of prepare for 2d

- docs/examples/basics/config.json
- docs/examples/basics/demo_Buniform_Ezero.jl
- docs/examples/basics/demo_ExB_drift.jl
- docs/examples/basics/demo_FLR.jl
- docs/examples/basics/demo_currentsheet.jl
- docs/examples/basics/demo_curvature_B.jl
- docs/examples/basics/demo_electron_proton.jl
- docs/examples/basics/demo_energy_conservation.jl
- docs/examples/basics/demo_ensemble.jl
- docs/examples/basics/demo_gradient_B.jl
- docs/examples/basics/demo_gravity_drift.jl
- docs/examples/basics/demo_magneticbottle.jl
- docs/examples/basics/demo_magneticmirror.jl
- docs/examples/basics/demo_multiple.jl
- docs/examples/basics/demo_polarization_drift.jl
- docs/examples/basics/demo_proton_dipole.jl
- docs/examples/basics/demo_tokamak_coil.jl
- docs/examples/basics/demo_tokamak_profile.jl
* Add two demos of energy conservations
* Fix source code hide syntax
> Add energy conservation demo

- docs/examples/basics/config.json
- docs/examples/basics/demo_boris.jl
- docs/examples/basics/demo_proton_dipole.jl
- src/TestParticle.jl
- src/pusher.jl
- test/runtests.jl
> Make `is_time_dependent` type stable

- Project.toml
- docs/examples/basics/demo_Buniform_Ezero.jl
- docs/examples/basics/demo_ExB_drift.jl
- docs/examples/basics/demo_FLR.jl
- docs/examples/basics/demo_curvature_B.jl
- docs/examples/basics/demo_ensemble.jl
- docs/examples/basics/demo_gradient_B.jl
- docs/examples/basics/demo_gravity_drift.jl
* Prepare for new minor version 0.4.0
* Update all the demos
> Bump minor version to 0.4.0

- Project.toml
> Bump Makie compat

- Project.toml
- ext/typerecipes.jl
- src/TestParticle.jl
- test/Project.toml
- test/test_Makie.jl
> Clean up dependencies

- .github/workflows/RecipeCI.yml
> Turn on recipe check

- ext/interactive.jl
- ext/typerecipes.jl
- src/TestParticle.jl
* Replace `t_min` and `t_max` with `t1` and `t2` to reflect the fact that `tspan` can be both ascending and descending.
* Grammar fixes
* Replace `x === nothing` with `isnothing(x)`
> Support interactive monitor for backward tracing

- Project.toml
- docs/examples/basics/config.json
- docs/examples/basics/demo_boris_outofdomain.jl
- src/pusher.jl
* Add a new demo for the Boris method combined with boundary check
* Update Meshes version compat
> Boris boundary

- .github/workflows/CI.yml
- .github/workflows/RecipeCI.yml
- .github/workflows/benchmark.yml
- Project.toml
- README.md
- benchmark/benchmarks.jl
- docs/examples/basics/demo_boris.jl
- docs/examples/basics/demo_boris_outofdomain.jl
- docs/examples/basics/demo_ensemble.jl
- docs/examples/basics/demo_proton_dipole.jl
- src/TestParticle.jl
- src/precompile.jl
- src/pusher.jl
- test/runtests.jl
* Reorganize Boris tmp variables for fixing multithreading errors
* Rename `trace_trajectory` --> `solve`
> Multithreading Boris tracing

- Project.toml
- src/precompile.jl
- src/pusher.jl
* Precompile threading branch for the Boris method
* Use MVectors for temporary vectors
* Add `@fastmath` and `@inbounds` for the outer loop
> Speeding up Boris

- docs/examples/advanced/config.json
- docs/examples/advanced/demo_shock.jl
Add a demo for tracing particles across the MHD perpendicular and parallel shocks. #19
> Add a shock demo

- docs/make.jl
- docs/src/plotfunctions.md
* Add remote repository link to every page in the documentation
* Fix some issues in the plot function doc
> Add repo link to docs

- src/pusher.jl
Simple adjustment to make backward in time Boris tracing possible.
> Allow backward Boris tracing

- docs/examples/advanced/config.json
- docs/examples/advanced/demo_gpu.md
Add a GPU demo. No CI is used since a GPU runner is required, and we don't have one right now.
Handle #170
> Add a GPU demo

- src/pusher.jl
- test/runtests.jl
> Support time-dependent field in Boris pusher

- Project.toml
- docs/examples/advanced/demo_cosmicray.jl
- src/prepare.jl
- test/runtests.jl
* Add show method for Field struct to avoid long type display
* Fix typos in the cosmic ray demo
> Interpolation extension

- docs/examples/advanced/demo_cosmicray.jl
The normalization in the 1st version doesn't look right. I further clarify the steps in this version.
> Fix cr normalization

- Project.toml
- docs/examples/advanced/demo_analytic_magnetosphere.jl
- docs/examples/advanced/demo_currentsheet.jl
- src/utility/current_sheet.jl
- test/runtests.jl
* Add a superposition of a Harris current sheet and a dipole field for tracing.
* Update the current sheet demo for better trajectory and field display.
> Update magnetosphere demo

- docs/examples/advanced/config.json
- docs/examples/advanced/demo_flux.jl
Add a demo for estimating particle flux.
> Add a flux demo

- .github/workflows/CI.yml
- docs/examples/basics/config.json
- docs/examples/basics/demo_array.md
Give a demo based on the question in #225.
> Add an array conversion demo

- src/TestParticle.jl
- src/equations.jl
- src/gc.jl
- src/prepare.jl
Please ignore the commit message, the feature is splitted from the PR
> refactor: simplify `prepare` codes
